common: &common
  adapter: postgresql
  username: bigsteamrobot
  password: kDtyHSAR

development:
  <<: *common
  database: big_steam_development
  host: localhost


test: &test
  <<: *common
  database: big_steam_test
  host: localhost

production:
  <<: *common
  database: big_steam_production

cucumber:
  <<: *test
